stages:
  - build
  - release

variables:
  NODE_VERSION: "18"

build_webui:
  stage: build
  image: node:$NODE_VERSION
  script:
    - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
    - . ~/.nvm/nvm.sh
    - nvm install $NODE_VERSION
    - nvm use $NODE_VERSION
    - yarn install
    - yarn bundle
  artifacts:
    paths:
      - bundle/
    expire_in: 1 hour

release_job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - echo "running release_job"
  release: # See https://docs.gitlab.com/ee/ci/yaml/#release for available properties
    tag_name: "$CI_COMMIT_TAG"
    description: "$CI_COMMIT_TAG"
