stages:
  - build
  - release

variables:
  NODE_VERSION: "18"

build_webui:
  stage: build
  image: node:$NODE_VERSION
  script:
    - export PACKAGE_VERSION=$(node -p "require('./package.json').version")
    - echo $PACKAGE_VERSION > version.txt
    - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
    - . ~/.nvm/nvm.sh
    - nvm install $NODE_VERSION
    - nvm use $NODE_VERSION
    - yarn install
    - yarn bundle
  artifacts:
    paths:
      - version.txt
      - bundle/webui-v${PACKAGE_VERSION}.zip
      - bundle/webui-v${PACKAGE_VERSION}.zip.sha256
    expire_in: 1 hour

release_job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - export PACKAGE_VERSION=$(cat version.txt)
    - echo "Releasing version $PACKAGE_VERSION"
  release: # See https://docs.gitlab.com/ee/ci/yaml/#release for available properties
    tag_name: "v$PACKAGE_VERSION"
    description: "Release v$PACKAGE_VERSION"
  artifacts:
    paths:
      - bundle/webui-v${PACKAGE_VERSION}.zip
      - bundle/webui-v${PACKAGE_VERSION}.zip.sha256
