stages:
  - build
  - release

variables:
  NODE_VERSION: "18"

build_webui:
  stage: build
  image: node:$NODE_VERSION
  script:
    - export PACKAGE_VERSION=$(node -p "require('./package.json').version")
    - export TAG_NAME=v$PACKAGE_VERSION
    - export RELEASE_NAME="Release $TAG_NAME"
    - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
    - . ~/.nvm/nvm.sh
    - nvm install $NODE_VERSION
    - nvm use $NODE_VERSION
    - yarn install
    - yarn bundle
  artifacts:
    paths:
      - bundle/webui-v${TAG_NAME}.zip
      - bundle/webui-v${TAG_NAME}.zip.sha256
    expire_in: 1 hour
  release: # See https://docs.gitlab.com/ee/ci/yaml/#release for available properties
    tag_name: "$TAG_NAME"
    description: "$RELEASE_NAME"
